// Vendors the OpenAPI spec generated by the bsms repo into ./openapi/openapi.json.
//
// The spec is generated from Zod in bsms (`npm run gen:openapi`). This copies it
// here and acts as a DRIFT GUARD: if the incoming spec differs from the committed
// copy, it says so — a changed API contract is a signal to review + regenerate
// types (and adjust tests), not something to absorb silently.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";

const src = process.env.BSMS_SPEC_PATH
  ? resolve(process.cwd(), process.env.BSMS_SPEC_PATH)
  : resolve(process.cwd(), "../bsms/openapi/openapi.json");
const dest = resolve(process.cwd(), "openapi/openapi.json");

if (!existsSync(src)) {
  console.error(
    `[sync-spec] source spec not found: ${src}\n` +
      `  Run \`npm run gen:openapi\` in the bsms repo, or set BSMS_SPEC_PATH.`
  );
  process.exit(1);
}

const incoming = readFileSync(src, "utf8");
const current = existsSync(dest) ? readFileSync(dest, "utf8") : null;

mkdirSync(dirname(dest), { recursive: true });

if (current === incoming) {
  console.log("[sync-spec] spec unchanged.");
} else {
  writeFileSync(dest, incoming);
  console.log(
    current === null
      ? "[sync-spec] vendored spec (new)."
      : "[sync-spec] spec UPDATED — the API contract changed. Review the diff, " +
          "re-run `npm run gen:types`, and check the tests still hold."
  );
}
